# Generated by Django 3.1.7 on 2021-03-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodClass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('dtime', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=14)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
